### ISSUE TITLE
⛰️ terrarium

### ISSUE THREAD

**Issue by PaulAroo** [benevolent-games/terrarium#1]
- [x] #2
- [x] #3
- [x] #4

**Comment by chase-moskal** [comment]
- make use the old readme concept for inspiration https://github.com/benevolent-games/makemake/tree/master/s/terrarium#readme

start fresh

```ts
export function makeTerrarium() {
	const oracle = makeOracle(settings)
	const actuator = makeActuator({oracle})
}
```

**Comment by chase-moskal** [comment]
![Image](https://user-images.githubusercontent.com/7145590/204931476-dc556d58-ed86-46aa-a7c5-587927381455.png)
